/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Attendance;

import static Attendance.searchclass.day_validation;
import static Attendance.searchclass.endtime_validation;
import static Attendance.searchclass.starttime_validation;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author shirow
 */
public class addclass extends javax.swing.JFrame {
    Connection conn = null; // connection to the database
    ResultSet rs = null;
    Statement st;
    PreparedStatement pst;
    PreparedStatement ps;
    /**
     * Creates new form addclass
     */
    public addclass() {
        initComponents();
        validatetextfield2();
        validatetextfield1();
        validatetextfield3();
    }
    
     private void validatetextfield1(){
        degree_name.addKeyListener(new KeyAdapter(){
			public void keyTyped(KeyEvent e){
				char ch = e.getKeyChar();
				if(Character.isDigit(ch)){
					degree_name.setText("");
					JOptionPane.showMessageDialog(null, "Input characters only!");
                                        degree_name.setText("");
                                }
			}

			
		});
    }
    
    private void validatetextfield2(){
        course_name.addKeyListener(new KeyAdapter(){
			public void keyTyped(KeyEvent e){
				char ch = e.getKeyChar();
				if(Character.isDigit(ch)){
					course_name.setText("");
					JOptionPane.showMessageDialog(null, "Input characters only!");
                                        course_name.setText("");
                                }
			}

			
		});
    }
    
     private void validatetextfield3(){
        admin_name.addKeyListener(new KeyAdapter(){
			public void keyTyped(KeyEvent e){
				char ch = e.getKeyChar();
				if(Character.isDigit(ch)){
					admin_name.setText("");
					JOptionPane.showMessageDialog(null, "Input characters only!");
                                        admin_name.setText("");
                                }
			}

			
		});
    }
    
     public static boolean day_validation(String classday)
    {
        boolean status = false;
        
        String classday_pattern = "^[a-zA-Z]+$";
        Pattern pattern = Pattern.compile(classday_pattern);
        Matcher matcher = pattern.matcher(classday);
        
        if (matcher.matches()){
            status = true;
        }
        else{
            status = false;
        }
        return status;
    }
     public static boolean starttime_validation(String starttime)
    {
        boolean status1 = false;
        
        String starttime_pattern = "^[0-1]{1}[0-9]{1}:[0-6]{1}[0-9]{1}:[0-1]{1}[0-9]{1}$";
        Pattern pattern = Pattern.compile(starttime_pattern);
        Matcher matcher = pattern.matcher(starttime);
        
        if (matcher.matches()){
            status1 = true;
        }
        else{
            status1 = false;
        }
        return status1;
    }
     public static boolean endtime_validation(String endtime)
    {
        boolean status2 = false;
        
        String endtime_pattern = "^[0-1]{1}[0-9]{1}:[0-6]{1}[0-9]{1}:[0-1]{1}[0-9]{1}$";
        Pattern pattern = Pattern.compile(endtime_pattern);
        Matcher matcher = pattern.matcher(endtime);
        
        if (matcher.matches()){
            status2 = true;
        }
        else{
            status2 = false;
        }
        return status2;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        class_day = new javax.swing.JTextField();
        start_time = new javax.swing.JTextField();
        end_time = new javax.swing.JTextField();
        course_name = new javax.swing.JTextField();
        degree_name = new javax.swing.JTextField();
        admin_name = new javax.swing.JTextField();
        savebtn = new javax.swing.JButton();
        course_id = new javax.swing.JTextField();
        degree_id = new javax.swing.JTextField();
        admin_id = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ampm = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 15)); // NOI18N
        jLabel1.setText("NEW CLASS");

        jLabel2.setText("Class day");

        jLabel3.setText("Start Time");

        jLabel4.setText("End Time");

        jLabel5.setText("Course Name");

        jLabel6.setText("Degree Name");

        jLabel7.setText("Admin Name");

        course_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                course_nameKeyReleased(evt);
            }
        });

        degree_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                degree_nameKeyReleased(evt);
            }
        });

        admin_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                admin_nameKeyReleased(evt);
            }
        });

        savebtn.setFont(new java.awt.Font("SansSerif", 2, 15)); // NOI18N
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        course_id.setEnabled(false);

        degree_id.setEnabled(false);

        admin_id.setEnabled(false);

        jLabel8.setText("AM/PM/AM-PM");

        jButton1.setFont(new java.awt.Font("SansSerif", 2, 15)); // NOI18N
        jButton1.setText("Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(admin_name)
                                    .addComponent(course_name)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(173, 173, 173)
                                        .addComponent(jButton1)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(76, 76, 76)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(start_time, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                    .addComponent(class_day, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(end_time)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(degree_name, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ampm)
                                        .addGap(191, 191, 191)))))))
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(course_id, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                        .addComponent(admin_id))
                    .addComponent(degree_id, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(class_day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(start_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(end_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ampm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(degree_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(degree_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(course_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(course_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(admin_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(admin_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void course_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_course_nameKeyReleased
         try {    
           DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            String dbURL = "jdbc:mysql://localhost:3306/user_info";
            String dbUser = "root";
            String dbPass = "shirow12";
            conn = DriverManager.getConnection(dbURL, dbUser, dbPass);   
        
        String c = course_name.getText();
        String sql2 = "SELECT course_id FROM courses WHERE courses.course_name = '"+c+"'";
        
        ps = conn.prepareStatement(sql2);
            rs =ps.executeQuery();
            while(rs.next()){
                
                course_id.setText(rs.getString("course_id"));
            }
        
                }
                catch(Exception e){JOptionPane.showMessageDialog(null, e);} 
    }//GEN-LAST:event_course_nameKeyReleased

    private void degree_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_degree_nameKeyReleased
         try {    
           DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            String dbURL = "jdbc:mysql://localhost:3306/user_info";
            String dbUser = "root";
            String dbPass = "shirow12";
            conn = DriverManager.getConnection(dbURL, dbUser, dbPass);   
        
        String d = degree_name.getText();
        String sql2 = "SELECT degree_id FROM degrees WHERE degrees.degree_name = '"+d+"'";
        
        ps = conn.prepareStatement(sql2);
            rs =ps.executeQuery();
            while(rs.next()){
                
                degree_id.setText(rs.getString("degree_id"));
            }
        
                }
                catch(Exception e){JOptionPane.showMessageDialog(null, e);} 
    }//GEN-LAST:event_degree_nameKeyReleased

    private void admin_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_admin_nameKeyReleased
         try {    
           DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            String dbURL = "jdbc:mysql://localhost:3306/user_info";
            String dbUser = "root";
            String dbPass = "shirow12";
            conn = DriverManager.getConnection(dbURL, dbUser, dbPass);   
        
        String a = admin_name.getText();
        String sql2 = "SELECT admin_id FROM admin WHERE admin.admin_name = '"+a+"'";
        
        ps = conn.prepareStatement(sql2);
            rs =ps.executeQuery();
            while(rs.next()){
                
                admin_id.setText(rs.getString("admin_id"));
            }
        
                }
                catch(Exception e){JOptionPane.showMessageDialog(null, e);} 
    }//GEN-LAST:event_admin_nameKeyReleased

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        String s1 = class_day.getText();
            String s2 = start_time.getText();
            String s3 = end_time.getText();
            String s7 = ampm.getText();
            String s4 = course_id.getText();
            String s5 = degree_id.getText();
            String s6 = admin_id.getText();
            
            if ("".equals(s1))
            {
                JOptionPane.showMessageDialog(savebtn, "INPUT CLASS DAY");
            }
            else if ("".equals(s2))
            {
                JOptionPane.showMessageDialog(savebtn, "INPUT START TIME");
            }
              else if ("".equals(s3))
            {
                JOptionPane.showMessageDialog(savebtn, "INPUT END TIME ");
            }
              else if ("".equals(s7))
            {
                JOptionPane.showMessageDialog(savebtn, "INPUT AM/PM/AM-PM");
            }
              else if ("".equals(s5))
            {
                JOptionPane.showMessageDialog(savebtn, "DEGREE BY THAT NAME DOES NOT EXIST");
            }
              else if ("".equals(s4))
            {
                JOptionPane.showMessageDialog(savebtn, "COURSE BY THAT NAME DOESN NOT EXIST");
            }
              else if ("".equals(s6))
            {
                JOptionPane.showMessageDialog(savebtn, "ADMIN BY THAT NAME DOES NOT EXIST");
            }
              
              else{
                  boolean status = day_validation(class_day.getText());
           if(status){
              
                  boolean status1 = starttime_validation(start_time.getText());
           if(status1){
                      
                  boolean status2 = endtime_validation(end_time.getText());
           if(status2){
               if (s1 .equals("Monday") || s1 .equals("Tuesday") || s1 .equals("Wednesday") || s1 .equals("Thursday") || s1 .equals("Friday")){
               if (s7 .equals("AM") || s7 .equals("PM") || s7 .equals("AM-PM")){ 
                       
              try {
                  conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user_info", "root", "shirow12");
                   String sql="INSERT INTO class(class_day,start_time,end_time,course_id,degree_id,admin_id,AM_PM) values(?,?,?,?,?,?,?)";
                    ps = conn.prepareStatement(sql);
                    ps.setString(1, s1);
                    ps.setString(2, s2);
                    ps.setString(3, s3);
                    ps.setString(4, s4);
                    ps.setString(5, s5);
                    ps.setString(6, s6);
                    ps.setString(7, s7);
                   
                    
                   int row = ps.executeUpdate();
                if (row > 0) {
                   JOptionPane.showMessageDialog(savebtn, "Class Saved Successfully");
                   dispose();
        new searchclass().setVisible(true);
                        }
                
                     else {
                         JOptionPane.showMessageDialog(savebtn, "error!!!");
                            }
             
                     }
               catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                    }
            class_day.setText("");
            start_time.setText("");
            end_time.setText("");
            course_name.setText("");
            course_id.setText("");
            degree_name.setText("");
            degree_id.setText("");
            admin_name.setText("");
            admin_id.setText("");
            
         }else{JOptionPane.showMessageDialog(savebtn, "ENTER EITHER AM/PM OR AM-PM IN CAPSLOCK");}
                    }else{JOptionPane.showMessageDialog(savebtn, "ENTER ANY WEEKDAYS ONLY e.g Monday");}
                      }else{
                      JOptionPane.showMessageDialog(savebtn, "ENTER END TIME IN THE WRITE FORMAT");
                      }
           }else{
                       JOptionPane.showMessageDialog(savebtn, "ENTER START TIME IN THE WRITE FORMAT");
                              }
           }else{
                              JOptionPane.showMessageDialog(savebtn, "ENTER DAY OF THE WEEK WITHOUT NUMBERS");
                              }
              }
            
    }//GEN-LAST:event_savebtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        new searchclass().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addclass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField admin_id;
    private javax.swing.JTextField admin_name;
    private javax.swing.JTextField ampm;
    private javax.swing.JTextField class_day;
    private javax.swing.JTextField course_id;
    private javax.swing.JTextField course_name;
    private javax.swing.JTextField degree_id;
    private javax.swing.JTextField degree_name;
    private javax.swing.JTextField end_time;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton savebtn;
    private javax.swing.JTextField start_time;
    // End of variables declaration//GEN-END:variables
}
