/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Attendance;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author shirow
 */
public class searchclass extends javax.swing.JFrame {
     Connection conn = null; // connection to the database
    ResultSet rs = null;
    Statement st;
    PreparedStatement pst;
    ResultSet res = null;
    PreparedStatement ps;
    PreparedStatement psd;
    PreparedStatement psa;
    /**
     * Creates new form searchclass
     */
    public searchclass() {
        initComponents();
        display_table();
        
    }
    
    public static boolean day_validation(String classday)
    {
        boolean status = false;
        
        String classday_pattern = "^[a-zA-Z]+$";
        Pattern pattern = Pattern.compile(classday_pattern);
        Matcher matcher = pattern.matcher(classday);
        
        if (matcher.matches()){
            status = true;
        }
        else{
            status = false;
        }
        return status;
    }
     public static boolean starttime_validation(String starttime)
    {
        boolean status1 = false;
        
        String starttime_pattern = "^[0-1]{1}[0-9]{1}:[0-6]{1}[0-9]{1}:[0-1]{1}[0-9]{1}$";
        Pattern pattern = Pattern.compile(starttime_pattern);
        Matcher matcher = pattern.matcher(starttime);
        
        if (matcher.matches()){
            status1 = true;
        }
        else{
            status1 = false;
        }
        return status1;
    }
     public static boolean endtime_validation(String endtime)
    {
        boolean status2 = false;
        
        String endtime_pattern = "^[0-1]{1}[0-9]{1}:[0-6]{1}[0-9]{1}:[0-1]{1}[0-9]{1}$";
        Pattern pattern = Pattern.compile(endtime_pattern);
        Matcher matcher = pattern.matcher(endtime);
        
        if (matcher.matches()){
            status2 = true;
        }
        else{
            status2 = false;
        }
        return status2;
    }
     
     private void display_table(){
         try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user_info", "root", "shirow12");
            st = conn.createStatement();
            String sql = "SELECT * FROM class";
            rs = st.executeQuery(sql);
            
            datatable.setModel(DbUtils.resultSetToTableModel(rs));
            
           
    }
    catch(Exception e){
                JOptionPane.showMessageDialog(null, "ERROR");
                }
        
    finally
    { 
        try
        {
            st.close(); rs.close(); conn.close(); 
        }
        catch(Exception e)
        { JOptionPane.showMessageDialog(null, "ERROR CLOSE"); }

    }      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        course_code = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        class_id = new javax.swing.JTextField();
        day = new javax.swing.JTextField();
        start_time = new javax.swing.JTextField();
        end_time = new javax.swing.JTextField();
        course_id = new javax.swing.JTextField();
        degree_id = new javax.swing.JTextField();
        admin_id = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        datatable = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        addbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        classday = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        am_pm = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 15)); // NOI18N
        jLabel1.setText("CLASSES AVAILABLE");

        jLabel2.setText("Enter course_code");

        jLabel3.setText("Search");

        course_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                course_codeKeyTyped(evt);
            }
        });

        jLabel4.setText("class_id");

        jLabel5.setText("Class day");

        jLabel6.setText("Start time");

        jLabel7.setText("End time");

        jLabel8.setText("Course id");

        jLabel9.setText("Degree id");

        jLabel10.setText("Admin id");

        class_id.setEnabled(false);

        course_id.setEnabled(false);

        degree_id.setEnabled(false);

        admin_id.setEnabled(false);

        datatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(datatable);

        jLabel11.setText("Enter class day");

        addbtn.setFont(new java.awt.Font("SansSerif", 2, 15)); // NOI18N
        addbtn.setText("ADD NEW CLASS");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        deletebtn.setFont(new java.awt.Font("SansSerif", 2, 15)); // NOI18N
        deletebtn.setText("DELETECLASS");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        updatebtn.setFont(new java.awt.Font("SansSerif", 2, 15)); // NOI18N
        updatebtn.setText("UPDATE CLASS");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        clearbtn.setFont(new java.awt.Font("SansSerif", 2, 15)); // NOI18N
        clearbtn.setText("CLEAR");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        classday.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                classdayKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                classdayKeyReleased(evt);
            }
        });

        jLabel12.setText("AM/PM");

        jButton1.setFont(new java.awt.Font("SansSerif", 2, 15)); // NOI18N
        jButton1.setText("Admin main");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(end_time)
                                    .addComponent(start_time)
                                    .addComponent(day)
                                    .addComponent(course_code)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(class_id, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(degree_id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(course_id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(280, 280, 280)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(10, 10, 10))
                                                .addComponent(addbtn, javax.swing.GroupLayout.Alignment.TRAILING))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(clearbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(updatebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(deletebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                                    .addComponent(classday, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(admin_id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(am_pm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(59, 59, 59)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(course_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(classday, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(class_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(addbtn)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(start_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deletebtn))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(end_time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(updatebtn)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(am_pm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(course_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(clearbtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(degree_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(admin_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classdayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classdayKeyReleased
         try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user_info", "root", "shirow12");
            String sql = "SELECT * FROM class INNER JOIN courses ON class.course_id = courses.course_id WHERE course_code = ? AND class_day = ?";
            pst = conn.prepareStatement(sql );
            pst.setString(1, course_code.getText());
            pst.setString(2, classday.getText());
           
            ResultSet result = pst.executeQuery();
            if(result.next()){
                String add1 = result.getString("class_id");
                class_id.setText(add1);
                String add2 = result.getString("class_day");
                day.setText(add2);
                String add3 = result.getString("start_time");
                start_time.setText(add3);
                String add4 = result.getString("end_time");
                end_time.setText(add4);
                String add8 = result.getString("AM_PM");
                am_pm.setText(add8);
                String add5 = result.getString("course_id");
                course_id.setText(add5);
                String add6 = result.getString("degree_id");
                degree_id.setText(add6);
                String add7 = result.getString("admin_id");
                admin_id.setText(add7);
            }
           
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, evt);
        }
        
    }//GEN-LAST:event_classdayKeyReleased

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        int p = JOptionPane.showConfirmDialog(null,"Do you want procede with deletion ?","Delete",JOptionPane.YES_NO_OPTION);
        if (p == 0){
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user_info", "root", "shirow12");
            String sqlquery = "delete from class where class_id =?";
            
            pst = conn.prepareStatement(sqlquery);
            
            pst.setString(1,class_id.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "DATA Deleted!!!");
                                 
    }
    catch(Exception e){
                JOptionPane.showMessageDialog(null,"CANNOT STUDENTS HAVE ATTENDED THE CLASS ");
                }
    finally
    { 
        try
        {
            st.close();
            rs.close(); 
            conn.close(); 
        }
        catch(Exception e)
        { JOptionPane.showMessageDialog(null, "ERROR!"); }

    }   
        }
        display_table();
            course_code.setText("");
            classday.setText("");
            class_id.setText("");
            day.setText("");
            start_time.setText("");
            end_time.setText("");
            course_id.setText("");
            degree_id.setText("");
            admin_id.setText("");
    }//GEN-LAST:event_deletebtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
            String value1 = class_id.getText();
             String value2 = day.getText();
              String value3 = start_time.getText();
               String value4 = end_time.getText();
               String value8 = am_pm.getText();
               String value5 = course_id.getText();
               String value6 = degree_id.getText();
               String value7 = admin_id.getText();
               if ("".equals(value2))
            {
                JOptionPane.showMessageDialog(updatebtn, "INPUT CLASS DAY");
            }
            else if ("".equals(value3))
            {
                JOptionPane.showMessageDialog(updatebtn, "INPUT START TIME");
            }
              else if ("".equals(value4))
            {
                JOptionPane.showMessageDialog(updatebtn, "INPUT END TIME ");
            }
              else if ("".equals(value8))
            {
                JOptionPane.showMessageDialog(updatebtn, "INPUT AM/PM/AM-PM");
            }
              
              else{
                  boolean status = day_validation(day.getText());
           if(status){
              
                  boolean status1 = starttime_validation(start_time.getText());
           if(status1){
                      
                  boolean status2 = endtime_validation(end_time.getText());
           if(status2){
               if (value2 .equals("Monday") || value2 .equals("Tuesday") || value2 .equals("Wednesday") || value2 .equals("Thursday") || value2 .equals("Friday")){
               if (value8 .equals("AM") || value8 .equals("PM") || value8 .equals("AM-PM")){ 
                       try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user_info", "root", "shirow12");
            String sql = "update class set class_id = '"+value1+"',class_day = '"+value2+"',start_time = '"+value3+"',end_time ='"+value4+"',course_id ='"+value5+"',degree_id ='"+value6+"',admin_id ='"+value7+"',AM_PM = '"+value8+"'where class_id = '"+value1+"'";
            
            pst = conn.prepareStatement(sql );
            pst.execute();
            JOptionPane.showMessageDialog(null, "update successfull");
               
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
         display_table();
            course_code.setText("");
            classday.setText("");
            class_id.setText("");
            day.setText("");
            start_time.setText("");
            end_time.setText("");
            course_id.setText("");
            degree_id.setText("");
            admin_id.setText("");
            am_pm.setText("");
                       }else{JOptionPane.showMessageDialog(updatebtn, "ENTER EITHER AM/PM OR AM-PM IN CAPSLOCK");}
                    }else{JOptionPane.showMessageDialog(updatebtn, "ENTER ANY WEEKDAYS ONLY e.g Monday");}
                      }else{
                      JOptionPane.showMessageDialog(updatebtn, "ENTER END TIME IN THE WRITE FORMAT");
                      }
           }else{
                       JOptionPane.showMessageDialog(updatebtn, "ENTER START TIME IN THE WRITE FORMAT");
                              }
           }else{
                              JOptionPane.showMessageDialog(updatebtn, "ENTER DAY OF THE WEEK WITHOUT NUMBERS");
                              }
              }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        dispose();
        new addclass().setVisible(true);
    }//GEN-LAST:event_addbtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
            course_code.setText("");
            classday.setText("");
            class_id.setText("");
            day.setText("");
            start_time.setText("");
            end_time.setText("");
            am_pm.setText("");
            course_id.setText("");
            degree_id.setText("");
            admin_id.setText("");
    }//GEN-LAST:event_clearbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        new admin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void course_codeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_course_codeKeyTyped
            classday.setText("");
            class_id.setText("");
            day.setText("");
            start_time.setText("");
            end_time.setText("");
            am_pm.setText("");
            course_id.setText("");
            degree_id.setText("");
            admin_id.setText("");
    }//GEN-LAST:event_course_codeKeyTyped

    private void classdayKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classdayKeyTyped
           
            class_id.setText("");
            day.setText("");
            start_time.setText("");
            end_time.setText("");
            course_id.setText("");
            degree_id.setText("");
            admin_id.setText("");
    }//GEN-LAST:event_classdayKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchclass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JTextField admin_id;
    private javax.swing.JTextField am_pm;
    private javax.swing.JTextField class_id;
    private javax.swing.JTextField classday;
    private javax.swing.JButton clearbtn;
    private javax.swing.JTextField course_code;
    private javax.swing.JTextField course_id;
    private javax.swing.JTable datatable;
    private javax.swing.JTextField day;
    private javax.swing.JTextField degree_id;
    private javax.swing.JButton deletebtn;
    private javax.swing.JTextField end_time;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField start_time;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
