/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Attendance;

import static Attendance.searchstudent.lastname_validation;
import static Attendance.searchstudent.reg_validation;
import static Attendance.searchstudent.text_validation;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author shirow
 */
public class searchdegree extends javax.swing.JFrame {
    
    Connection conn = null; // connection to the database
    ResultSet rs = null;
    Statement st;
    PreparedStatement pst;

    /**
     * Creates new form searchdegree
     */
    public searchdegree() {
        initComponents();
        display_table();
        validatetextfield();
    }
    private void validatetextfield(){
        degree_name.addKeyListener(new KeyAdapter(){
			public void keyTyped(KeyEvent e){
				char ch = e.getKeyChar();
				if(Character.isDigit(ch)){
					degree_name.setText("");
					JOptionPane.showMessageDialog(null, "Input characters only!");
                                        degree_name.setText("");
                                }
			}

			
		});
    }
    public static boolean degreetype_validation(String degreetype)
    {
        boolean status = false;
        
        String degreetype_pattern = "^[a-zA-Z]+$";
        Pattern pattern = Pattern.compile(degreetype_pattern);
        Matcher matcher = pattern.matcher(degreetype);
        
        if (matcher.matches()){
            status = true;
        }
        else{
            status = false;
        }
        return status;
    }
    public static boolean degreeduration_validation(String degreeduration)
    {
        boolean status2 = false;
        
        String degreeduration_pattern = "^[0-9]+$";
        Pattern pattern = Pattern.compile(degreeduration_pattern);
        Matcher matcher = pattern.matcher(degreeduration);
        
        if (matcher.matches()){
            status2 = true;
        }
        else{
            status2 = false;
        }
        return status2;
    }
     private void display_table(){
         try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user_info", "root", "shirow12");
            st = conn.createStatement();
            String sql = "SELECT * FROM degrees";
            rs = st.executeQuery(sql);
            
            datatable.setModel(DbUtils.resultSetToTableModel(rs));
            
           
    }
    catch(Exception e){
                JOptionPane.showMessageDialog(null, "ERROR");
                }
        
    finally
    { 
        try
        {
            st.close(); rs.close(); conn.close(); 
        }
        catch(Exception e)
        { JOptionPane.showMessageDialog(null, "ERROR CLOSE"); }

    }      

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        degreesearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        degree_id = new javax.swing.JTextField();
        degree_name = new javax.swing.JTextField();
        degree_type = new javax.swing.JTextField();
        degree_duration = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        datatable = new javax.swing.JTable();
        addbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 18)); // NOI18N
        jLabel1.setText("Degrees ");

        jLabel2.setText("Enter degree name to search");

        degreesearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                degreesearchKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                degreesearchKeyReleased(evt);
            }
        });

        jLabel3.setText("degree_id");

        jLabel4.setText("degree_name");

        jLabel5.setText("degree_type");

        jLabel6.setText("degree_duration");

        degree_id.setEnabled(false);

        datatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(datatable);

        addbtn.setFont(new java.awt.Font("SansSerif", 2, 15)); // NOI18N
        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        deletebtn.setFont(new java.awt.Font("SansSerif", 2, 15)); // NOI18N
        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        updatebtn.setFont(new java.awt.Font("SansSerif", 2, 15)); // NOI18N
        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        clearbtn.setFont(new java.awt.Font("SansSerif", 2, 15)); // NOI18N
        clearbtn.setText("CLEAR");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("SansSerif", 2, 15)); // NOI18N
        jButton1.setText("Admin main");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("click to exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(degree_id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(degree_name, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                                    .addComponent(degree_type))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(addbtn)
                                    .addComponent(deletebtn)
                                    .addComponent(updatebtn)
                                    .addComponent(clearbtn)))
                            .addComponent(degreesearch, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(degree_duration, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(136, 136, 136))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(271, 271, 271))))
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(degreesearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(degree_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addbtn))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(degree_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(deletebtn)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(degree_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(degree_duration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(updatebtn)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(38, 38, 38))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
      dispose();
        new adddegree().setVisible(true);
      
    }//GEN-LAST:event_addbtnActionPerformed

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
       String id = degree_id.getText();
        if ("".equals(id))
            {
                JOptionPane.showMessageDialog(deletebtn, "CANNOT DELETE EMPTY FIELDS");
            }
        else{
        int p = JOptionPane.showConfirmDialog(null,"Do you want procede with deletion ?","Delete",JOptionPane.YES_NO_OPTION);
        if (p == 0){
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user_info", "root", "shirow12");
            String sqlquery = "delete from degrees where degree_id =?";
            
            pst = conn.prepareStatement(sqlquery);
            
            pst.setString(1,degree_id.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "DATA Deleted!!!");
                                 
    }
    catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
                }
    finally
    { 
        try
        {
            st.close();
            rs.close(); 
            conn.close(); 
        }
        catch(Exception e)
        { JOptionPane.showMessageDialog(null, "ERROR!"); }

    }   
        }
        display_table();
            degree_id.setText("");
            degreesearch.setText("");
            degree_name.setText("");
            degree_type.setText("");
            degree_duration.setText("");
        }
    }//GEN-LAST:event_deletebtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
       String id = degree_id.getText();
        if ("".equals(id))
            {
                JOptionPane.showMessageDialog(deletebtn, "CANNOT UPDATE EMPTY FIELDS");
            }
        else{
        
            
            String value1 = degree_id.getText();
             String value2 = degree_name.getText();
              String value3 = degree_type.getText();
               String value4 = degree_duration.getText();
               
               
                boolean status = degreetype_validation(degree_type.getText());
                    if (status)
                    {
                        boolean status2 = degreeduration_validation(degree_duration.getText());
                    if (status2)
                    {
              
      try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user_info", "root", "shirow12");
            String sql = "update degrees set degree_id = '"+value1+"',degree_name = '"+value2+"',degree_type = '"+value3+"',degree_duration ='"+value4+"'where degree_id = '"+value1+"'";
            
            pst = conn.prepareStatement(sql );
            pst.execute();
            JOptionPane.showMessageDialog(null, "update successfull");
               
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
         display_table();   
            degree_id.setText("");
            degreesearch.setText("");
            degree_name.setText("");
            degree_type.setText("");
            degree_duration.setText("");
            }else{
               JOptionPane.showMessageDialog(updatebtn, "INPUT ONLY NUMBERS IN DEGREE DURATION TEXTFIELD"); 
           }
           }else{
               JOptionPane.showMessageDialog(updatebtn, "INPUT ONLY CHARACTERS IN DEGREE TYPE TEXTFIELD"); 
           }
        
        }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed

            degree_id.setText("");
            degreesearch.setText("");
            degree_name.setText("");
            degree_type.setText("");
            degree_duration.setText("");
    }//GEN-LAST:event_clearbtnActionPerformed

    private void degreesearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_degreesearchKeyReleased
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user_info", "root", "shirow12");
            String sql = "SELECT * FROM degrees WHERE degree_name = ?";
            pst = conn.prepareStatement(sql );
            pst.setString(1, degreesearch.getText());
           
            ResultSet result = pst.executeQuery();
            if(result.next()){
                String add1 = result.getString("degree_id");
                degree_id.setText(add1);
                String add2 = result.getString("degree_name");
                degree_name.setText(add2);
                String add3 = result.getString("degree_type");
                degree_type.setText(add3);
                String add4 = result.getString("degree_duration");
                degree_duration.setText(add4);
            }
            
               
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, evt);
            
        }
    }//GEN-LAST:event_degreesearchKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         dispose();
        new admin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void degreesearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_degreesearchKeyTyped
            degree_id.setText("");
            degree_name.setText("");
            degree_type.setText("");
            degree_duration.setText("");
            
    }//GEN-LAST:event_degreesearchKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchdegree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchdegree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchdegree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchdegree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchdegree().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton clearbtn;
    private javax.swing.JTable datatable;
    private javax.swing.JTextField degree_duration;
    private javax.swing.JTextField degree_id;
    private javax.swing.JTextField degree_name;
    private javax.swing.JTextField degree_type;
    private javax.swing.JTextField degreesearch;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updatebtn;
    // End of variables declaration//GEN-END:variables
}
