/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Attendance;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author shirow
 */
public class searchcourse extends javax.swing.JFrame {
    
     Connection conn = null; // connection to the database
    ResultSet rs = null;
    Statement st;
    PreparedStatement pst;
    PreparedStatement psd;

    /**
     * Creates new form searchdegree
     */
    public searchcourse() {
        initComponents();
        display_table();
    }
    
     private void validatetextfield(){
        course_name.addKeyListener(new KeyAdapter(){
			public void keyTyped(KeyEvent e){
				char ch = e.getKeyChar();
				if(Character.isDigit(ch)){
					course_name.setText("");
					JOptionPane.showMessageDialog(null, "Input characters only!");
                                        course_name.setText("");
                                }
			}

			
		});
    }
    public static boolean code_validation(String coursecode)
    {
        boolean status = false;
        
        String coursecode_pattern = "^[a-zA-Z]{3}\\s[0-9]{2,3}+$";
        Pattern pattern = Pattern.compile(coursecode_pattern);
        Matcher matcher = pattern.matcher(coursecode);
        
        if (matcher.matches()){
            status = true;
        }
        else{
            status = false;
        }
        return status;
    }
     public static boolean numofc_validation(String numofc)
    {
        boolean status1 = false;
        
        String numofc_pattern = "^[0-9]+$";
        Pattern pattern = Pattern.compile(numofc_pattern);
        Matcher matcher = pattern.matcher(numofc);
        
        if (matcher.matches()){
            status1 = true;
        }
        else{
            status1 = false;
        }
        return status1;
    }
     public static boolean year_validation(String year)
    {
        boolean status2 = false;
        
        String year_pattern = "^[1-6]+$";
        Pattern pattern = Pattern.compile(year_pattern);
        Matcher matcher = pattern.matcher(year);
        
        if (matcher.matches()){
            status2 = true;
        }
        else{
            status2 = false;
        }
        return status2;
    }
     public static boolean semester_validation(String semester)
    {
        boolean status3 = false;
        
        String semester_pattern = "^[1-2]+$";
        Pattern pattern = Pattern.compile(semester_pattern);
        Matcher matcher = pattern.matcher(semester);
        
        if (matcher.matches()){
            status3 = true;
        }
        else{
            status3 = false;
        }
        return status3;
    }

    private void display_table(){
         try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user_info", "root", "shirow12");
            st = conn.createStatement();
            String sql = "SELECT * FROM courses";
            rs = st.executeQuery(sql);
            
            datatable.setModel(DbUtils.resultSetToTableModel(rs));
            
           
    }
    catch(Exception e){
                JOptionPane.showMessageDialog(null, "ERROR");
                }
        
    finally
    { 
        try
        {
            st.close(); rs.close(); conn.close(); 
        }
        catch(Exception e)
        { JOptionPane.showMessageDialog(null, "ERROR CLOSE"); }

    }      

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        coursesearch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        course_id = new javax.swing.JTextField();
        course_code = new javax.swing.JTextField();
        course_name = new javax.swing.JTextField();
        number_of_classes = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        semester = new javax.swing.JTextField();
        degree_id = new javax.swing.JTextField();
        addbtn = new javax.swing.JButton();
        deletebtn = new javax.swing.JButton();
        updatebtn = new javax.swing.JButton();
        clearbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        datatable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 3, 15)); // NOI18N
        jLabel1.setText("COURSES OFFERED");

        jLabel2.setText("Enter course name");

        jLabel3.setText("search");

        coursesearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                coursesearchKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                coursesearchKeyReleased(evt);
            }
        });

        jLabel4.setText("Course id");

        jLabel5.setText("Course code");

        jLabel6.setText("Course name");

        jLabel7.setText("Number of classes");

        jLabel8.setText("Year");

        jLabel9.setText("Semester");

        jLabel10.setText("Degree  id");

        course_id.setEnabled(false);

        degree_id.setEnabled(false);

        addbtn.setFont(new java.awt.Font("SansSerif", 2, 15)); // NOI18N
        addbtn.setText("ADD");
        addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbtnActionPerformed(evt);
            }
        });

        deletebtn.setFont(new java.awt.Font("SansSerif", 2, 15)); // NOI18N
        deletebtn.setText("DELETE");
        deletebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletebtnActionPerformed(evt);
            }
        });

        updatebtn.setFont(new java.awt.Font("SansSerif", 2, 15)); // NOI18N
        updatebtn.setText("UPDATE");
        updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatebtnActionPerformed(evt);
            }
        });

        clearbtn.setFont(new java.awt.Font("SansSerif", 2, 15)); // NOI18N
        clearbtn.setText("CLEAR");
        clearbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbtnActionPerformed(evt);
            }
        });

        datatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(datatable);

        jButton1.setText("admin main");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setText("click to exit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(coursesearch, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(degree_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                                        .addComponent(semester, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(year, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 246, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(deletebtn)
                                        .addComponent(updatebtn)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(course_code, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                        .addGap(93, 93, 93)
                                                        .addComponent(clearbtn))
                                                    .addComponent(course_id, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(15, 15, 15)))
                                        .addComponent(number_of_classes, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(course_name, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addbtn))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(coursesearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(course_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(course_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(course_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(number_of_classes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(addbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(degree_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(deletebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(updatebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearbtn)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel11)))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       dispose();
        new admin().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void coursesearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coursesearchKeyReleased
       try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user_info", "root", "shirow12");
            String sql = "SELECT * FROM courses WHERE course_name = ?";
            pst = conn.prepareStatement(sql );
            pst.setString(1, coursesearch.getText());
           
            ResultSet result = pst.executeQuery();
            if(result.next()){
                String add1 = result.getString("course_id");
                course_id.setText(add1);
                String add2 = result.getString("course_code");
                course_code.setText(add2);
                String add3 = result.getString("course_name");
                course_name.setText(add3);
                String add4 = result.getString("course_hours");
                number_of_classes.setText(add4);
                String add5 = result.getString("year");
                year.setText(add5);
                String add6 = result.getString("semester");
                semester.setText(add6);
                String add7 = result.getString("degree_id");
                degree_id.setText(add7);
            }
            
               
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, evt);
            
        }
        
    }//GEN-LAST:event_coursesearchKeyReleased

    private void deletebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletebtnActionPerformed
        int p = JOptionPane.showConfirmDialog(null,"Do you want procede with deletion ?","Delete",JOptionPane.YES_NO_OPTION);
        if (p == 0){
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user_info", "root", "shirow12");
            String sqlquery = "delete from courses  WHERE course_id =?";
            
            pst = conn.prepareStatement(sqlquery);
            
            pst.setString(1,course_id.getText());
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "DATA Deleted!!!");
                                 
    }
    catch(Exception e){
                JOptionPane.showMessageDialog(null, "CANNOT DELETE CLASSES EXIST ON THAT COURSE");
                dispose();
        new admin().setVisible(true);
                }
    finally
    { 
        try
        {
            st.close();
            rs.close(); 
            conn.close(); 
        }
        catch(Exception e)
        { JOptionPane.showMessageDialog(null, "ERROR!"); }

    }   
        }
        display_table();
            coursesearch.setText("");
            course_id.setText("");
            course_name.setText("");
            course_code.setText("");
            number_of_classes.setText("");
            year.setText("");
            semester.setText("");
            degree_id.setText("");
    }//GEN-LAST:event_deletebtnActionPerformed

    private void updatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatebtnActionPerformed
       
            String value1 = course_id.getText();
             String value2 = course_code.getText();
              String value3 = course_name.getText();
               String value4 = number_of_classes.getText();
               String value5 = year.getText();
               String value6 = semester.getText();
               String value7 = degree_id.getText();
      if ("".equals(value2))
            {
                JOptionPane.showMessageDialog(updatebtn, "INPUT COURSE CODE");
            }
            else if ("".equals(value3))
            {
                JOptionPane.showMessageDialog(updatebtn, "INPUT COURSE NAME");
            }
              else if ("".equals(value4))
            {
                JOptionPane.showMessageDialog(updatebtn, "INPUT NUMBER OF CLASSES ");
            }
              else if ("".equals(value5))
            {
                JOptionPane.showMessageDialog(updatebtn, "INPUT YEAR OF SPECIFIC COURSE");
            }
              else if ("".equals(value6))
            {
                JOptionPane.showMessageDialog(updatebtn, "INPUT SEMESTER OF SPECIFIC COURSE ");
            }
              else{
                  boolean status = code_validation(course_code.getText());
           if(status){
              
               boolean status1 = numofc_validation(number_of_classes.getText());
                    if (status1)
                    {
                         boolean status2 = year_validation(year.getText());
                    if (status2)
                    {
                      boolean status3 = year_validation(semester.getText());
                    if (status3)
                    {  
                  try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/user_info", "root", "shirow12");
            String sql = "update courses set course_id = '"+value1+"',course_code = '"+value2+"',course_name = '"+value3+"',number_of classes ='"+value4+"',year ='"+value5+"',semester ='"+value6+"',degree_id ='"+value7+"'where course_id = '"+value1+"'";
            
            pst = conn.prepareStatement(sql );
            pst.execute();
            JOptionPane.showMessageDialog(null, "update successfull");
               
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
         display_table();
            coursesearch.setText("");
            course_id.setText("");
            course_name.setText("");
            course_code.setText("");
            number_of_classes.setText("");
            year.setText("");
            semester.setText("");
            degree_id.setText("");
            }else{
                        JOptionPane.showMessageDialog(updatebtn," ENTER ONLY SEMESTER 1 OR 2");
                    }
                    }else{
                        JOptionPane.showMessageDialog(updatebtn," ENTER ONLY YEAR BETWEEN 1 AND 6");
                    }
                    }else{
                        JOptionPane.showMessageDialog(updatebtn," ENTER ONLY NUMBERS FOR NUMBER_OF_CLASSES");
                    }
                    }else{
                        JOptionPane.showMessageDialog(updatebtn," ENTER COURSE CODE IN THE RIGHT FORMAT");
                    }
              }
    }//GEN-LAST:event_updatebtnActionPerformed

    private void clearbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbtnActionPerformed
            coursesearch.setText("");
            course_id.setText("");
            course_name.setText("");
            course_code.setText("");
            number_of_classes.setText("");
            year.setText("");
            semester.setText("");
            degree_id.setText("");
    }//GEN-LAST:event_clearbtnActionPerformed

    private void addbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbtnActionPerformed
        dispose();
        new addcourse().setVisible(true);
    }//GEN-LAST:event_addbtnActionPerformed

    private void coursesearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_coursesearchKeyTyped

            course_id.setText("");
            course_name.setText("");
            course_code.setText("");
            number_of_classes.setText("");
            year.setText("");
            semester.setText("");
            degree_id.setText("");
    }//GEN-LAST:event_coursesearchKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchcourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchcourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchcourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchcourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchcourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbtn;
    private javax.swing.JButton clearbtn;
    private javax.swing.JTextField course_code;
    private javax.swing.JTextField course_id;
    private javax.swing.JTextField course_name;
    private javax.swing.JTextField coursesearch;
    private javax.swing.JTable datatable;
    private javax.swing.JTextField degree_id;
    private javax.swing.JButton deletebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField number_of_classes;
    private javax.swing.JTextField semester;
    private javax.swing.JButton updatebtn;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
