/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Attendance;

import static java.awt.Color.BLACK;
import static java.awt.Color.white;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.ValueMarker;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.chart.title.TextTitle;
import org.jfree.data.jdbc.JDBCCategoryDataset;
import org.jfree.ui.TextAnchor;
import org.opencv.core.Core;

/**
 *
 * @author shirow
 */
public class studentreports extends javax.swing.JFrame {
    Connection conn; // connection to the database
    ResultSet rs;
    Statement st;
    PreparedStatement ps;
    static void reg_num(String text) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * Creates new form studentreports
     */
    public studentreports() {
        initComponents();
        filltextfield();
        
    }
    public void filltextfield(){
            try{
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            String dbURL = "jdbc:mysql://localhost:3306/user_info";
            String dbUser = "root";
            String dbPass = "shirow12";
            conn = DriverManager.getConnection(dbURL, dbUser, dbPass); 
        
   
         reg_num.getDocument().addDocumentListener(new DocumentListener()  {
             @Override
    public void insertUpdate(DocumentEvent e) {
        try {    
        String z = (String) reg_num.getText();
        
        System.out.println("registration number: " + reg_num.getText());
        String sql2 = "SELECT firstname,lastname,student_id FROM student WHERE registration_number ='"+z+"'";
         
        ps = conn.prepareStatement(sql2);
            rs =ps.executeQuery();
            while(rs.next()){
                
                firstname.setText(rs.getString("firstname"));
                lastname.setText(rs.getString("lastname"));
                student_id.setText(rs.getString("student_id"));
            }
        
                }
                catch(Exception evt){JOptionPane.showMessageDialog(null, "ERROR");}    
    
         }

                @Override
                public void changedUpdate(DocumentEvent de) {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }

                @Override
                public void removeUpdate(DocumentEvent de) {
                    throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
                }
     });
            }
        catch(Exception e){JOptionPane.showMessageDialog(null, "ERROR");} 
        }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        course_code = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        reg_num = new javax.swing.JTextField();
        reportbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        firstname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        course_name = new javax.swing.JTextField();
        reportbtn1 = new javax.swing.JButton();
        student_id = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        attended_classes = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        remaining_classes = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        remarks = new javax.swing.JTextField();
        totalclasses = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        notification = new javax.swing.JTextField();
        success = new javax.swing.JTextField();
        exambtn = new javax.swing.JButton();
        course_id = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        degree_name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ATTENDANCE REPORTS");

        jLabel2.setText("Sort by course to generate evaluation  report:");

        course_code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                course_codeKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                course_codeKeyReleased(evt);
            }
        });

        jLabel3.setText("registration_number");

        jLabel4.setText("student:");

        reg_num.setEnabled(false);

        reportbtn.setText("general attendance report");
        reportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportbtnActionPerformed(evt);
            }
        });

        jLabel5.setText("Names");

        firstname.setEnabled(false);

        jLabel6.setText("Input course code");

        jLabel7.setText("OR");

        jLabel8.setText("Input course name");

        course_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                course_nameKeyReleased(evt);
            }
        });

        reportbtn1.setText("REPORT BASED ON COURSE");
        reportbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportbtn1ActionPerformed(evt);
            }
        });

        student_id.setEnabled(false);

        lastname.setEnabled(false);

        jLabel9.setText("YOU HAVE ATTENDED ");

        attended_classes.setEnabled(false);

        jLabel10.setText("OUT OF ");

        remaining_classes.setEnabled(false);

        jLabel11.setText("TO GO!");

        remarks.setEnabled(false);

        totalclasses.setEnabled(false);

        jLabel12.setText("CLASSES");

        jLabel13.setText("You can only seat for exam if given this notification: ");

        notification.setText("You may seat for this course exam!!");
        notification.setEnabled(false);

        success.setEnabled(false);

        exambtn.setText("click to verify exam");
        exambtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exambtnActionPerformed(evt);
            }
        });

        course_id.setEnabled(false);

        jLabel14.setText("click to see your report");

        degree_name.setEnabled(false);
        degree_name.setOpaque(false);

        jButton1.setText("student main");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel9)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(attended_classes, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(totalclasses, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(remaining_classes, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(reportbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(degree_name, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(41, 41, 41)
                                                .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(reg_num, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                            .addComponent(lastname))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(course_code, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(2, 2, 2)
                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(75, 75, 75)
                                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(35, 35, 35)
                                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(25, 25, 25)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(course_name, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(reportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(student_id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(course_id, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(69, 69, 69)))
                .addGap(0, 73, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(202, 202, 202)
                .addComponent(exambtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(205, 205, 205)
                .addComponent(notification, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(success, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(remarks, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reg_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(firstname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(student_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(reportbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(course_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(course_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(reportbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(degree_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attended_classes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalclasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remaining_classes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(remarks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(notification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exambtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(success, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportbtnActionPerformed
       try{
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            String dbURL = "jdbc:mysql://localhost:3306/user_info";
            String dbUser = "root";
            String dbPass = "shirow12";
            conn = DriverManager.getConnection(dbURL, dbUser, dbPass); 
        try {
           
           String sql = "SELECT courses.course_name,count(attendance_date) FROM attendance INNER JOIN class ON attendance.class_id = class.class_id INNER JOIN courses ON class.course_id = courses.course_id WHERE student_id = '"+ student_id.getText() + "' GROUP BY courses.course_name";
           JDBCCategoryDataset dataset = new JDBCCategoryDataset(conn,sql);
           JFreeChart chart = ChartFactory.createBarChart3D("Student General report","courses","number of attended classes", dataset, PlotOrientation.VERTICAL, false, true, true);
           BarRenderer renderer = null;
           chart.setBackgroundPaint(white);
           CategoryPlot plot = chart.getCategoryPlot();
           renderer = new BarRenderer();
           ChartFrame frame = new ChartFrame("Student General report",chart);
           
           ValueMarker marker = new ValueMarker(24);
           marker.setLabel(" YOU MAY SEAT FOR EXAM IF BEYOND THIS LINE!");
           marker.setLabelTextAnchor(TextAnchor.TOP_RIGHT);
           marker.setPaint(BLACK);
           plot.addRangeMarker(marker);
           
           frame.setVisible(true);
           frame.setSize(1000,650);
       }
       catch(Exception e){
         JOptionPane.showMessageDialog(null, e);  
       }
        }
        catch(Exception e){JOptionPane.showMessageDialog(null, e);} 
    }//GEN-LAST:event_reportbtnActionPerformed

    private void reportbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportbtn1ActionPerformed
        try{
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            String dbURL = "jdbc:mysql://localhost:3306/user_info";
            String dbUser = "root";
            String dbPass = "shirow12";
            conn = DriverManager.getConnection(dbURL, dbUser, dbPass);
            if ("".equals(course_code.getText()))
            {
                JOptionPane.showMessageDialog(reportbtn1, "INPUT COURSE CODE");
            }
            else if ("".equals(course_name.getText()))
            {
                JOptionPane.showMessageDialog(reportbtn1, "INPUT COURSE NAME");
            }
            else{
        try {
            String query ="SELECT degrees.degree_name FROM attendance INNER JOIN class ON attendance.class_id = class.class_id INNER JOIN courses ON class.course_id = courses.course_id INNER JOIN degrees ON class.degree_id = degrees.degree_id WHERE student_id = '19' AND course_code = 'csc111' GROUP BY courses.course_name";
             ps = conn.prepareStatement(query);
            rs =ps.executeQuery();
            while(rs.next()){
                
                degree_name.setText(rs.getString("degree_name"));
            }
            
            String sql = "SELECT courses.course_name,count(attendance_date) FROM attendance INNER JOIN class ON attendance.class_id = class.class_id INNER JOIN courses ON class.course_id = courses.course_id WHERE student_id = '"+ student_id.getText() + "' AND course_code = '"+ course_code.getText() + "' GROUP BY courses.course_name";
           JDBCCategoryDataset dataset = new JDBCCategoryDataset(conn,sql);
           JFreeChart chart = ChartFactory.createBarChart3D("Student General report","courses","number of attended classes", dataset, PlotOrientation.VERTICAL, false, true, true);
           BarRenderer renderer = null;
           chart.addSubtitle(new TextTitle(new Date().toString()));
           chart.addSubtitle(new TextTitle(degree_name.getText()));
           chart.setBackgroundPaint(white);
           CategoryPlot plot = chart.getCategoryPlot();
           renderer = new BarRenderer();
           ChartFrame frame = new ChartFrame("Student General report",chart);
           
           ValueMarker marker = new ValueMarker(24);
           marker.setLabel(" YOU MAY SEAT FOR EXAM IF BEYOND THIS LINE!");
           marker.setLabelTextAnchor(TextAnchor.TOP_RIGHT);
           marker.setPaint(BLACK);
           plot.addRangeMarker(marker);
           
           frame.setVisible(true);
           frame.setSize(450,650);
       }
       catch(Exception e){
         JOptionPane.showMessageDialog(null, e);  
       }
        }
        }
        catch(SQLException | HeadlessException e){JOptionPane.showMessageDialog(null, e);} 
    }//GEN-LAST:event_reportbtn1ActionPerformed

    private void course_codeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_course_codeKeyReleased
        try{
            // connects to the database
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            String dbURL = "jdbc:mysql://localhost:3306/user_info";
            String dbUser = "root";
            String dbPass = "shirow12";
            conn = DriverManager.getConnection(dbURL, dbUser, dbPass);
            
            try {    
        String c = (String) course_code.getText();
        st = conn.createStatement();
            String sqlc="SELECT course_name,course_id FROM courses WHERE course_code = '"+c+"'";
            
             rs = st.executeQuery(sqlc);

             while(rs.next()){
                 
             course_name.setText(rs.getString("course_name"));
             course_id.setText(rs.getString("course_id"));

             }

          }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

            } 
            try {    
        String att = (String) course_code.getText();
       st = conn.createStatement();
            String sqlc = "SELECT count(attendance.verification)FROM attendance INNER JOIN class ON attendance.class_id = class.class_id INNER JOIN courses ON class.course_id = courses.course_id WHERE course_code = '"+att+"' AND student_id = '"+student_id.getText()+"'";
;
           rs = st.executeQuery(sqlc);

             while(rs.next()){
                 
             attended_classes.setText(rs.getString("count(attendance.verification)"));

             }

          }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

            }
            try {    
        String total = (String) course_code.getText();
       st = conn.createStatement();
            String sqlt = "SELECT number_of_classes FROM courses  WHERE course_code = '"+total+"'";

           rs = st.executeQuery(sqlt);

             while(rs.next()){
             
             totalclasses.setText(rs.getString("number_of_classes"));

             }

          }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

            }finally {
            try{
              rs.close();
                  st.close();
                 conn.close();
              }
              catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
                               }
                  }
         }
            catch(SQLException | HeadlessException e){

            JOptionPane.showMessageDialog(null, e);

            }
    int int1 = Integer.parseInt(attended_classes.getText());
    System.out.println("attended classes: " + int1);
    int int2 = Integer.parseInt(totalclasses.getText());
     System.out.println("total classes: " + int2);
    if (!attended_classes.equals("") || !totalclasses.getText().equals("") ) {
        remaining_classes.setText(String.valueOf(int2-int1));
    }
    int int3 = Integer.parseInt(attended_classes.getText());
    if( int3 < 24 ){
        remarks.setText("You cannot seat for this course exam!!");
    }
    else{
        remarks.setText("You may seat for this course exam!!");
    }
       
    }//GEN-LAST:event_course_codeKeyReleased

    private void course_nameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_course_nameKeyReleased
        try{
            // connects to the database
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            String dbURL = "jdbc:mysql://localhost:3306/user_info";
            String dbUser = "root";
            String dbPass = "shirow12";
            conn = DriverManager.getConnection(dbURL, dbUser, dbPass);
            
            try {    
        String n = (String) course_name.getText();
       st = conn.createStatement();
            String sqlc = "SELECT course_code,course_id FROM courses WHERE course_name = '"+n+"'";
           rs = st.executeQuery(sqlc);

             while(rs.next()){
                 
             course_code.setText(rs.getString("course_code"));
             course_id.setText(rs.getString("course_id"));
             }

          }catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

            }
            finally {
            try{
              rs.close();
                  st.close();
                 conn.close();
              }
              catch(Exception e) {
                JOptionPane.showMessageDialog(null, e);
                               }
                  }
         }
            catch(Exception e){

            JOptionPane.showMessageDialog(null, e);

            }
    }//GEN-LAST:event_course_nameKeyReleased

    private void exambtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exambtnActionPerformed
        try{
            // connects to the database
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());
            String dbURL = "jdbc:mysql://localhost:3306/user_info";
            String dbUser = "root";
            String dbPass = "shirow12";
            conn = DriverManager.getConnection(dbURL, dbUser, dbPass);
            
            String s1 = student_id.getText();
            String s2 = remarks.getText();
            String s3 = notification.getText();
            String s4 = course_id.getText();
            System.out.println ("Remarks:" + s2);
            System.out.println ("notifications:" + s3);
    
            if (s2.equals(s3))
           {
               try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost/user_info", "root", "shirow12");
            ps = conn.prepareStatement("SELECT `student_id`, `course_code` FROM `examverification` WHERE `student_id` = ? AND `course_code` = ?");
            ps.setString(1, student_id.getText());
            ps.setString(2, course_code.getText());
            ResultSet result = ps.executeQuery();
            if(result.next()){
                JOptionPane.showMessageDialog(exambtn, "YOU HAVE ALREADY VERIFIED THE EXAM OF THIS COURSE");
                
            }
            else{
                try
               {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/user_info", "root", "shirow12");
                   String sqle="INSERT INTO examverification(student_id,verfication_text,course_id) values(?,?,?)";
                    PreparedStatement ps = con.prepareStatement(sqle);
                    ps.setString(1, s1);
                    ps.setString(2, s2);
                    ps.setString(3, s4);
                    
                   int row = ps.executeUpdate();
                if (row > 0) {
                        success.setText("YOU HAVE SUCCESSFULLY VERIFIED THIS COURSE EXAM, SUCCESS!!!");
                        }
                     else {
                          success.setText("FAIL");
                            }
             
                     }
                               catch (ClassNotFoundException | SQLException | HeadlessException ex) {
                                {
                                    System.out.println("Found some error : " + ex);
                                     }
                    }
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, evt);
            
        }
            
           }
                else
                    {
                 success.setText("ATTEND MORE CLASSES");
                    }
        }
        catch(SQLException | HeadlessException e){

            JOptionPane.showMessageDialog(null, e);

            } 
        
    }//GEN-LAST:event_exambtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        new Student().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void course_codeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_course_codeKeyTyped
            course_name.setText("");
            course_id.setText("");
            degree_name.setText("");
            attended_classes.setText("");
            totalclasses.setText("");
            remaining_classes.setText("");
            remarks.setText("");
            success.setText("");
    }//GEN-LAST:event_course_codeKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentreports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentreports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentreports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentreports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentreports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attended_classes;
    private javax.swing.JTextField course_code;
    private javax.swing.JTextField course_id;
    private javax.swing.JTextField course_name;
    private javax.swing.JTextField degree_name;
    private javax.swing.JButton exambtn;
    private javax.swing.JTextField firstname;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField notification;
    public static javax.swing.JTextField reg_num;
    private javax.swing.JTextField remaining_classes;
    private javax.swing.JTextField remarks;
    private javax.swing.JButton reportbtn;
    private javax.swing.JButton reportbtn1;
    private javax.swing.JTextField student_id;
    private javax.swing.JTextField success;
    private javax.swing.JTextField totalclasses;
    // End of variables declaration//GEN-END:variables
}
